version: "3.9"

services:
  fe:
    image: captrivia-fe
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
  be:
    image: captrivia-be
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_TTL_SEC: 300
      COUNTDOWN_DURATION_SEC: 5
      QUESTION_DURATION_SEC: 10
      QUESTIONS_FILE_PATH: "/app/questions.json"

  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"